sandbox/library/urls.py
from django.urls import path, re_path
from django.views import generic

from library import views

app_name = "library"
urlpatterns = [
    re_path(r'^$', generic.TemplateView.as_view(template_name="library/index.html"), name="index"),
    re_path(r'^authors$', views.AuthorListView.as_view(), name="authors"),
    re_path(r'^author/(?P<pk>a_[0-9a-zA-Z]+)/$', views.AuthorDetailView.as_view(), name="author-detail"),
    re_path(r'^books$', views.BookListView.as_view(), name="books"),
    re_path(r'^book/add/$', views.BookCreateView.as_view(), name="book-create"),
    re_path(r'^book/(?P<pk>[0-9a-zA-Z]+)/edit/$', views.BookUpdateView.as_view(), name="book-update"),
    re_path(r'^book/(?P<pk>[0-9a-zA-Z]+)/$', views.BookDetailView.as_view(), name="book-detail"),
]

sandbox/sandbox/urls.py
from django.urls import path, include
from django.contrib import admin

from rest_framework import routers

from library import views as library_views

router = routers.DefaultRouter()
router.register('authors', library_views.AuthorViewSet)
router.register('books', library_views.BookViewSet)

urlpatterns = [
    path('', include('library.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

sandbox/core/models.py
from django.conf import settings
from django.contrib.flatpages.models import FlatPage
from hashids import Hashids
from hashid_field import HashidAutoField

field = FlatPage._meta.fields[0]
field.__class__ = HashidAutoField
field.salt = settings.HASHID_FIELD_SALT
field.min_length = 7
field.alphabet = Hashids.ALPHABET
field.allow_int_lookup = True

sandbox/library/models.py
from django.db import models

from hashid_field import HashidAutoField, HashidField, BigHashidAutoField, BigHashidField

from django.urls import reverse


class Author(models.Model):
    id = BigHashidAutoField(primary_key=True, prefix="a_", alphabet="0123456789abcdef")
    name = models.CharField(max_length=40)
    uid = models.UUIDField(null=True, blank=True)
    id_str = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.id_str = str(self.id)
        super().save(*args, **kwargs)


class Editor(models.Model):
    id = HashidAutoField(primary_key=True, salt="A different salt", min_length=20)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=40)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True, related_name='books')
    reference_id = HashidField(salt="alternative salt", allow_int_lookup=True, prefix="ref_")
    key = HashidField(min_length=10, alphabet="abcdlmnotuvwxyz0123789", null=True, blank=True, default=1)
    alt = HashidField(min_length=10, enable_hashid_object=False, null=True, blank=True)
    some_number = models.IntegerField(null=True, blank=True)
    editors = models.ManyToManyField(Editor, blank=True)

    def get_absolute_url(self):
        return reverse("library:book-detail", kwargs={'pk': self.pk})

    def __str__(self):
        return "{} ({})".format(self.name, self.reference_id)

sandbox/library/forms.py
from django import forms

from library.models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('name', 'author', 'reference_id', 'key', 'alt', 'some_number', 'editors')
        # widgets = {
        #     'author': forms.TextInput()
        # }

sandbox/core/views.py
from django.shortcuts import render

# Create your views here.

sandbox/library/views.py
from django.views import generic
from rest_framework import viewsets

from library.forms import BookForm
from library.models import Author, Book
from library.serializers import AuthorSerializer, BookSerializer


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author


class BookListView(generic.ListView):
    model = Book


class BookDetailView(generic.DetailView):
    model = Book


class BookCreateView(generic.CreateView):
    model = Book
    form_class = BookForm


class BookUpdateView(generic.UpdateView):
    model = Book
    form_class = BookForm


class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.order_by('id')
    serializer_class = AuthorSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.order_by('id')
    serializer_class = BookSerializer

sandbox/library/templates/library/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Author {{ object.name }}</title>
</head>
<body>

<h1>{{ object.name }} ({{ object.id }})</h1>
<p>UID: {{ object.uid }}</p>

<h2>Books</h2>
<ul>
    {% for book in object.books.all %}
        <li><a href="{% url "library:book-detail" pk=book.id %}">{{ book.name }}</a></li>
    {% endfor %}
</ul>

</body>
</html>

sandbox/library/templates/library/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Authors</title>
</head>
<body>

<ul>
    {% for author in object_list %}
        <li><a href="{% url "library:author-detail" pk=author.id %}">{{ author.name }}</a></li>
    {% endfor %}
</ul>

</body>
</html>

sandbox/library/templates/library/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Book {{ object.name }}</title>
</head>
<body>

<h1>
    {{ object.name }} ({{ object.id }})
    <small>
        <a href="{% url "library:book-update" pk=object.pk %}">[edit]</a>
    </small>
</h1>
<p>Author: <a href="{% url "library:author-detail" pk=object.author.id %}">{{ object.author }}</a></p>
<p>Reference ID: {{ object.reference_id }}</p>
<p>Key: {{ object.key }}</p>
<p>Alt: {{ object.alt }}</p>
<p>Some Number: {{ object.some_number }}</p>

<h2>Editors</h2>
<ul>
    {% for editor in object.editors.all %}
        <li>{{ editor.name }}</li>
    {% empty %}
        <li>None</li>
    {% endfor %}
</ul>

</body>
</html>

sandbox/library/templates/library/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Books</title>
</head>
<body>

<h1>Add/Edit book</h1>

<form action="" method="post">{% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Submit">
</form>

</body>
</html>

sandbox/library/templates/library/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Books</title>
</head>
<body>

<ul>
    {% for book in object_list %}
        <li><a href="{% url "library:book-detail" pk=book.id %}">{{ book.name }}</a></li>
    {% endfor %}
</ul>

<a href="{% url "library:book-create" %}">Add book</a>
</body>
</html>

sandbox/library/templates/library/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library</title>
</head>
<body>

<ul>
    <li><a href="{% url "library:authors" %}">Authors</a></li>
    <li><a href="{% url "library:books" %}">Books</a></li>
    <li><a href="{% url "api-root" %}">API</a></li>
</ul>

</body>
</html>